---
title: "ARIMA National University of Singapore"
author: "BAYU"
date: "2023-06-08"
output: word_document
---

1.  Aktifkan beberapa library

```{r}
library(TSA)
library(forecast)
```

2.  Membaca dataset

```{r}
data3<-read.csv("C:/Users/bayuk/OneDrive/Documents/AI/pens/smtr2/Permodelan Statistika/uas/singapore.csv",header=TRUE)
data3<-data3$scores_teaching
head(data3)
```

3.  Plot time series data University of Hong Kong

```{r}
ts.plot(data3, xlab="Time Period ", ylab="scores_teaching", main= "Time Series Plot Data National University of Singapore")
points(data3)
```

4.  Uji Formal Stasioneritas Data

```{r}
tseries::adf.test(ts(data3))
```

5.  Spesifikasi Model: Plot ACF

```{r}
acf(ts(data3))
pacf(ts(data3))
```

6.  Estimasi model

```{r}
model.arma11<-arima(ts(data3), order = c(1,0,1), method = "ML")
lmtest::coeftest(model.arma11)
model.ar2<-arima(ts(data3), order = c(2,0,0), method = "ML")
lmtest::coeftest(model.ar2)
model.arma21<-arima(ts(data3), order = c(2,0,1), method = "ML")
lmtest::coeftest(model.arma21)
model.arma21b<-arima(ts(data3), order = c(2,0,1), method = "ML",include.mean=F)
lmtest::coeftest(model.arma21b)
model.sarma200001_6<-arima(ts(data3), order = c(2,0,0), 
seasonal=list(order=c(0,0,1),period=6),method = "ML")
lmtest::coeftest(model.sarma200001_6)
model.sarma201001_6<-arima(ts(data3), order = c(2,0,1), 
seasonal=list(order=c(0,0,1),period=6),method = "ML")
lmtest::coeftest(model.sarma201001_6)
model.sarma200002_6<-arima(ts(data3), order = c(2,0,0), 
seasonal=list(order=c(0,0,2),period=6),method = "ML")
lmtest::coeftest(model.sarma200002_6)
```

6.  Diagnosa Model

```{r}
(aic.model<-data.frame(
Model = c("ARMA11","AR2","ARMA21","SARMA201001"),
AIC = c(model.arma11$aic, model.arma21$aic, 
model.arma21$aic,model.sarma201001_6$aic),
sigma2 = c(model.arma11$sigma2, model.arma21$sigma2, 
model.arma21$sigma2,model.sarma201001_6$sigma2)))
```

```{r}
sisaan <- model.sarma201001_6$residuals
# Eksplorasi
par(mfrow=c(2,2))
qqnorm(sisaan)
qqline(sisaan, col = "blue", lwd = 2)
plot(c(1:length(sisaan)),sisaan)
acf(sisaan)
pacf(sisaan)
```

```{r}
# Uji formal normalitas data
ks.test(sisaan,"pnorm")
```

```{r}
# Uji nilai tengah sisaan
t.test(sisaan, mu = 0, alternative = "two.sided")
```

```{r}
# Uji autokorelasi
Box.test(sisaan, lag = 23 ,type = "Ljung")
```

```{r}
#Overfitting Model1
model.sarma201001_6<-arima(ts(data3), order = c(2,0,1), seasonal=list(order=c(0,0,1),period=6),method = "ML")
lmtest::coeftest(model.sarma201001_6)

#Overfitting Model2
model.sarma200003_6<-arima(ts(data3), order = c(2,0,0), seasonal=list(order=c(0,0,3),period=6),method = "ML")
lmtest::coeftest(model.sarma200003_6)
```

```{r}
#Peramalan
(ramalan<- forecast::forecast(ts(data3),model=model.sarma201001_6, h=7))
```

```{r}
plot(ramalan)
```
